//! Instructions for Cancun.

use crate::{opcodes, Group, OpCode, Upgrade};

opcodes! {
    Cancun,
    (0x00, STOP, 0, 0, 0, "Halts execution.", Frontier, StopArithmetic),
    (0x01, ADD, 3, 2, 1, "Addition operation.", Frontier, StopArithmetic),
    (0x02, MUL, 5, 2, 1, "Multiplication operation.", Frontier, StopArithmetic),
    (0x03, SUB, 3, 2, 1, "Subtraction operation.", Frontier, StopArithmetic),
    (0x04, DIV, 5, 2, 1, "Integer division operation.", Frontier, StopArithmetic),
    (0x05, SDIV, 5, 2, 1, "Signed integer division operation (truncated).", Frontier, StopArithmetic),
    (0x06, MOD, 5, 2, 1, "Modulo remainder operation.", Frontier, StopArithmetic),
    (0x07, SMOD, 5, 2, 1, "Signed modulo remainder operation.", Frontier, StopArithmetic),
    (0x08, ADDMOD, 8, 3, 1, "Modulo addition operation.", Frontier, StopArithmetic),
    (0x09, MULMOD, 8, 3, 1, "Modulo multiplication operation.", Frontier, StopArithmetic),
    (0x0a, EXP, 10, 2, 1, "Exponential operation.", Frontier, StopArithmetic),
    (0x0b, SIGNEXTEND, 5, 2, 1, "Extend length of two's complement signed integer.", Frontier, StopArithmetic),
    (0x10, LT, 3, 2, 1, "Less-than comparison.", Frontier, ComparisonBitwiseLogic),
    (0x11, GT, 3, 2, 1, "Greater-than comparison.", Frontier, ComparisonBitwiseLogic),
    (0x12, SLT, 3, 2, 1, "Signed less-than comparison.", Frontier, ComparisonBitwiseLogic),
    (0x13, SGT, 3, 2, 1, "Signed greater-than comparison.", Frontier, ComparisonBitwiseLogic),
    (0x14, EQ, 3, 2, 1, "Equality comparison.", Frontier, ComparisonBitwiseLogic),
    (0x15, ISZERO, 3, 1, 1, "Simple not operator.", Frontier, ComparisonBitwiseLogic),
    (0x16, AND, 3, 2, 1, "Bitwise AND operation.", Frontier, ComparisonBitwiseLogic),
    (0x17, OR, 3, 2, 1, "Bitwise OR operation.", Frontier, ComparisonBitwiseLogic),
    (0x18, XOR, 3, 2, 1, "Bitwise XOR operation.", Frontier, ComparisonBitwiseLogic),
    (0x19, NOT, 3, 1, 1, "Bitwise NOT operation.", Frontier, ComparisonBitwiseLogic),
    (0x1a, BYTE, 3, 2, 1, "Retrieve single byte from word.", Frontier, ComparisonBitwiseLogic),
    (0x1b, SHL, 3, 2, 1, "Left shift operation", Constantinople, ComparisonBitwiseLogic),
    (0x1c, SHR, 3, 2, 1, "Logical right shift operation", Constantinople, ComparisonBitwiseLogic),
    (0x1d, SAR, 3, 2, 1, "Arithmetic (signed) right shift operation", Constantinople, ComparisonBitwiseLogic),
    (0x20, KECCAK256, 30, 2, 1, "Compute Keccak-256 hash.", Frontier, StopArithmetic),
    (0x30, ADDRESS, 2, 0, 1, "Get address of currently executing account.", Frontier, EnvironmentalInformation),
    (0x31, BALANCE, 20, 1, 1, "Get balance of the given account.", Frontier, EnvironmentalInformation),
    (0x32, ORIGIN, 2, 0, 1, "Get execution origination address.", Frontier, EnvironmentalInformation),
    (0x33, CALLER, 2, 0, 1, "Get caller address.", Frontier, EnvironmentalInformation),
    (0x34, CALLVALUE, 2, 0, 1, "Get deposited value by the instruction/transaction responsible for this execution.", Frontier, EnvironmentalInformation),
    (0x35, CALLDATALOAD, 3, 1, 1, "Get input data of current environment.", Frontier, EnvironmentalInformation),
    (0x36, CALLDATASIZE, 2, 0, 1, "Get size of input data in current environment.", Frontier, EnvironmentalInformation),
    (0x37, CALLDATACOPY, 3, 3, 0, "Copy input data in current environment to memory.", Frontier, EnvironmentalInformation),
    (0x38, CODESIZE, 2, 0, 1, "Get size of code running in current environment.", Frontier, EnvironmentalInformation),
    (0x39, CODECOPY, 3, 3, 0, "Copy code running in current environment to memory.", Frontier, EnvironmentalInformation),
    (0x3a, GASPRICE, 2, 0, 1, "Get price of gas in current environment", Frontier, EnvironmentalInformation),
    (0x3b, EXTCODESIZE, 20, 1, 1, "Get size of an account's code.", Frontier, EnvironmentalInformation),
    (0x3c, EXTCODECOPY, 20, 4, 0, "Copy an account's code to memory.", Frontier, EnvironmentalInformation),
    (0x3d, RETURNDATASIZE, 2, 0, 1, "Get size of output data from the previous call from the current environment.", Byzantium, EnvironmentalInformation),
    (0x3e, RETURNDATACOPY, 3, 3, 0, "Copy output data from the previous call to memory.", Byzantium, EnvironmentalInformation),
    (0x3f, TSTORE, 100, 2, 0, "Store word in transient storage.", Cancun, EnvironmentalInformation),
    (0x40, TLOAD, 100, 1, 1, "Load word from transient storage.", Cancun, EnvironmentalInformation),
    (0x41, COINBASE, 2, 0, 1, "Get the block's beneficiary address.", Frontier, BlockInformation),
    (0x42, TIMESTAMP, 2, 0, 1, "Get the block's timestamp.", Frontier, BlockInformation),
    (0x43, NUMBER, 2, 0, 1, "Get the block's number.", Frontier, BlockInformation),
    (0x44, DIFFICULTY, 2, 0, 1, "Get the block's difficulty.", Frontier, BlockInformation),
    (0x45, GASLIMIT, 2, 0, 1, "Get the block's gas limit.", Frontier, BlockInformation),
    (0x46, CHAINID, 2, 0, 1, "Get the chain ID.", Istanbul, BlockInformation),
    (0x47, SELFBALANCE, 5, 0, 1, "Get balance of currently executing account.", Istanbul, BlockInformation),
    (0x48, BASEFEE, 2, 0, 1, "Get the base fee.", London, BlockInformation),
    (0x49, BLOBHASH, 3, 1, 1, "Get versioned hash at index.", Cancun, BlockInformation),
    (0x4a, BLOBBASEFEE, 2, 0, 1, "Get the current blob base fee.", Cancun, BlockInformation),
    (0x50, POP, 2, 1, 0, "Remove item from stack.", Frontier, StackMemoryStorageFlow),
    (0x51, MLOAD, 3, 1, 1, "Load word from memory.", Frontier, StackMemoryStorageFlow),
    (0x52, MSTORE, 3, 2, 0, "Save word to memory.", Frontier, StackMemoryStorageFlow),
    (0x53, MSTORE8, 3, 2, 0, "Save byte to memory.", Frontier, StackMemoryStorageFlow),
    (0x54, SLOAD, 50, 1, 1, "Load word from storage.", Frontier, StackMemoryStorageFlow),
    (0x55, SSTORE, 0, 2, 0, "Save word to storage.", Frontier, StackMemoryStorageFlow),
    (0x56, JUMP, 8, 1, 0, "Alter the program counter.", Frontier, StackMemoryStorageFlow),
    (0x57, JUMPI, 10, 2, 0, "Conditionally alter the program counter.", Frontier, StackMemoryStorageFlow),
    (0x58, PC, 2, 0, 1, "Get the value of the program counter prior to the increment.", Frontier, StackMemoryStorageFlow),
    (0x59, MSIZE, 2, 0, 1, "Get the size of active memory in bytes.", Frontier, StackMemoryStorageFlow),
    (0x5a, GAS, 2, 0, 1, "Get the amount of available gas.", Frontier, StackMemoryStorageFlow),
    (0x5b, JUMPDEST, 1, 0, 0, "Mark a valid destination for jumps.", Frontier, StackMemoryStorageFlow),
    (0x5f, PUSH0, 2, 0, 1, "Place 0 byte item on stack.", Shanghai, Push),
    // PUSH1 through SWAP16 remain unchanged from Shanghai
    // Including all PUSH, DUP, and SWAP operations (0x60-0x9f)
    (0xa0, LOG0, 375, 2, 0, "Append log record with no topics.", Frontier, Logging),
    (0xa1, LOG1, 750, 3, 0, "Append log record with one topic.", Frontier, Logging),
    (0xa2, LOG2, 1125, 4, 0, "Append log record with two topics.", Frontier, Logging),
    (0xa3, LOG3, 1500, 5, 0, "Append log record with three topics.", Frontier, Logging),
    (0xa4, LOG4, 1875, 6, 0, "Append log record with four topics.", Frontier, Logging),
    (0xf0, CREATE, 32000, 3, 1, "Create a new account with associated code.", Frontier, System),
    (0xf1, CALL, 100, 7, 1, "Message-call into an account.", Frontier, System),
    (0xf2, CALLCODE, 100, 7, 1, "Message-call into this account with alternative account's code.", Frontier, System),
    (0xf3, RETURN, 0, 2, 0, "Halt execution returning output data.", Frontier, System),
    (0xf4, DELEGATECALL, 40, 6, 1, "Message-call with an alternative account's code, persisting the current context.", Frontier, System),
    (0xf5, CREATE2, 32000, 4, 1, "Create a new account with associated code at a specified address.", Constantinople, System),
    (0xfa, STATICCALL, 40, 6, 1, "Static message-call into an account.", Byzantium, System),
    (0xfb, MCOPY, 3, 3, 0, "Copy memory to memory.", Cancun, System),
    (0xfd, REVERT, 0, 2, 0, "Stop execution and revert state changes, without consuming all gas and providing a reason.", Byzantium, System),
    (0xfe, INVALID, 0, 0, 0, "Designated invalid instruction.", Frontier, System),
    (0xff, SELFDESTRUCT, 5000, 1, 0, "Halt execution and register account for later deletion.", Frontier, System)
}