//! Ethereum virtual machine opcode

/// Ethereum virtual machine opcode.
#[derive(Clone, Copy, Debug)]
pub enum OpCode {
    STOP,
    ADD,
    MUL,
    SUB,
    DIV,
    SDIV,
    MOD,
    SMOD,
    ADDMOD,
    MULMOD,
    EXP,
    SIGNEXTEND,
    LT,
    GT,
    SLT,
    SGT,
    EQ,
    ISZERO,
    AND,
    OR,
    XOR,
    NOT,
    BYTE,
    SHL,
    SHR,
    SAR,
    SHA3,
    ADDRESS,
    BALANCE,
    ORIGIN,
    CALLER,
    CALLVALUE,
    CALLDATALOAD,
    CALLDATASIZE,
    CALLDATACOPY,
    CODESIZE,
    CODECOPY,
    GASPRICE,
    EXTCODESIZE,
    EXTCODECOPY,
    RETURNDATASIZE,
    RETURNDATACOPY,
    EXTCODEHASH,
    BLOCKHASH,
    COINBASE,
    TIMESTAMP,
    NUMBER,
    DIFFICULTY,
    GASLIMIT,
    CHAINID,
    SELFBALANCE,
    BASEFEE,
    POP,
    MLOAD,
    MSTORE,
    MSTORE8,
    SLOAD,
    SSTORE,
    JUMP,
    JUMPI,
    PC,
    MSIZE,
    GAS,
    JUMPDEST,
    PUSH0,
    PUSH1,
    PUSH2,
    PUSH3,
    PUSH4,
    PUSH5,
    PUSH6,
    PUSH7,
    PUSH8,
    PUSH9,
    PUSH10,
    PUSH11,
    PUSH12,
    PUSH13,
    PUSH14,
    PUSH15,
    PUSH16,
    PUSH17,
    PUSH18,
    PUSH19,
    PUSH20,
    PUSH21,
    PUSH22,
    PUSH23,
    PUSH24,
    PUSH25,
    PUSH26,
    PUSH27,
    PUSH28,
    PUSH29,
    PUSH30,
    PUSH31,
    PUSH32,
    DUP1,
    DUP2,
    DUP3,
    DUP4,
    DUP5,
    DUP6,
    DUP7,
    DUP8,
    DUP9,
    DUP10,
    DUP11,
    DUP12,
    DUP13,
    DUP14,
    DUP15,
    DUP16,
    SWAP1,
    SWAP2,
    SWAP3,
    SWAP4,
    SWAP5,
    SWAP6,
    SWAP7,
    SWAP8,
    SWAP9,
    SWAP10,
    SWAP11,
    SWAP12,
    SWAP13,
    SWAP14,
    SWAP15,
    SWAP16,
    LOG0,
    LOG1,
    LOG2,
    LOG3,
    LOG4,
    CREATE,
    CALL,
    CALLCODE,
    RETURN,
    DELEGATECALL,
    CREATE2,
    STATICCALL,
    REVERT,
    INVALID,
    SELFDESTRUCT,
}

impl From<u8> for OpCode {
    fn from(code: u8) -> Self {
        match code {
            0x00 => Self::STOP,
            0x01 => Self::ADD,
            0x02 => Self::MUL,
            0x03 => Self::SUB,
            0x04 => Self::DIV,
            0x05 => Self::SDIV,
            0x06 => Self::MOD,
            0x07 => Self::SMOD,
            0x08 => Self::ADDMOD,
            0x09 => Self::MULMOD,
            0x0a => Self::EXP,
            0x0b => Self::SIGNEXTEND,
            0x10 => Self::LT,
            0x11 => Self::GT,
            0x12 => Self::SLT,
            0x13 => Self::SGT,
            0x14 => Self::EQ,
            0x15 => Self::ISZERO,
            0x16 => Self::AND,
            0x17 => Self::OR,
            0x18 => Self::XOR,
            0x19 => Self::NOT,
            0x1a => Self::BYTE,
            0x1b => Self::SHL,
            0x1c => Self::SHR,
            0x1d => Self::SAR,
            0x20 => Self::SHA3,
            0x30 => Self::ADDRESS,
            0x31 => Self::BALANCE,
            0x32 => Self::ORIGIN,
            0x33 => Self::CALLER,
            0x34 => Self::CALLVALUE,
            0x35 => Self::CALLDATALOAD,
            0x36 => Self::CALLDATASIZE,
            0x37 => Self::CALLDATACOPY,
            0x38 => Self::CODESIZE,
            0x39 => Self::CODECOPY,
            0x3a => Self::GASPRICE,
            0x3b => Self::EXTCODESIZE,
            0x3c => Self::EXTCODECOPY,
            0x3d => Self::RETURNDATASIZE,
            0x3e => Self::RETURNDATACOPY,
            0x3f => Self::EXTCODEHASH,
            0x40 => Self::BLOCKHASH,
            0x41 => Self::COINBASE,
            0x42 => Self::TIMESTAMP,
            0x43 => Self::NUMBER,
            0x44 => Self::DIFFICULTY,
            0x45 => Self::GASLIMIT,
            0x46 => Self::CHAINID,
            0x47 => Self::SELFBALANCE,
            0x48 => Self::BASEFEE,
            0x50 => Self::POP,
            0x51 => Self::MLOAD,
            0x52 => Self::MSTORE,
            0x53 => Self::MSTORE8,
            0x54 => Self::SLOAD,
            0x55 => Self::SSTORE,
            0x56 => Self::JUMP,
            0x57 => Self::JUMPI,
            0x58 => Self::PC,
            0x59 => Self::MSIZE,
            0x5a => Self::GAS,
            0x5b => Self::JUMPDEST,
            0x5f => Self::PUSH0,
            0x60 => Self::PUSH1,
            0x61 => Self::PUSH2,
            0x62 => Self::PUSH3,
            0x63 => Self::PUSH4,
            0x64 => Self::PUSH5,
            0x65 => Self::PUSH6,
            0x66 => Self::PUSH7,
            0x67 => Self::PUSH8,
            0x68 => Self::PUSH9,
            0x69 => Self::PUSH10,
            0x6a => Self::PUSH11,
            0x6b => Self::PUSH12,
            0x6c => Self::PUSH13,
            0x6d => Self::PUSH14,
            0x6e => Self::PUSH15,
            0x6f => Self::PUSH16,
            0x70 => Self::PUSH17,
            0x71 => Self::PUSH18,
            0x72 => Self::PUSH19,
            0x73 => Self::PUSH20,
            0x74 => Self::PUSH21,
            0x75 => Self::PUSH22,
            0x76 => Self::PUSH23,
            0x77 => Self::PUSH24,
            0x78 => Self::PUSH25,
            0x79 => Self::PUSH26,
            0x7a => Self::PUSH27,
            0x7b => Self::PUSH28,
            0x7c => Self::PUSH29,
            0x7d => Self::PUSH30,
            0x7e => Self::PUSH31,
            0x7f => Self::PUSH32,
            0x80 => Self::DUP1,
            0x81 => Self::DUP2,
            0x82 => Self::DUP3,
            0x83 => Self::DUP4,
            0x84 => Self::DUP5,
            0x85 => Self::DUP6,
            0x86 => Self::DUP7,
            0x87 => Self::DUP8,
            0x88 => Self::DUP9,
            0x89 => Self::DUP10,
            0x8a => Self::DUP11,
            0x8b => Self::DUP12,
            0x8c => Self::DUP13,
            0x8d => Self::DUP14,
            0x8e => Self::DUP15,
            0x8f => Self::DUP16,
            0x90 => Self::SWAP1,
            0x91 => Self::SWAP2,
            0x92 => Self::SWAP3,
            0x93 => Self::SWAP4,
            0x94 => Self::SWAP5,
            0x95 => Self::SWAP6,
            0x96 => Self::SWAP7,
            0x97 => Self::SWAP8,
            0x98 => Self::SWAP9,
            0x99 => Self::SWAP10,
            0x9a => Self::SWAP11,
            0x9b => Self::SWAP12,
            0x9c => Self::SWAP13,
            0x9d => Self::SWAP14,
            0x9e => Self::SWAP15,
            0x9f => Self::SWAP16,
            0xa0 => Self::LOG0,
            0xa1 => Self::LOG1,
            0xa2 => Self::LOG2,
            0xa3 => Self::LOG3,
            0xa4 => Self::LOG4,
            0xf0 => Self::CREATE,
            0xf1 => Self::CALL,
            0xf2 => Self::CALLCODE,
            0xf3 => Self::RETURN,
            0xf4 => Self::DELEGATECALL,
            0xf5 => Self::CREATE2,
            0xfa => Self::STATICCALL,
            0xfd => Self::REVERT,
            0xfe => Self::INVALID,
            0xff => Self::SELFDESTRUCT,
            _ => Self::INVALID,
        }
    }
}

impl From<OpCode> for u16 {
    fn from(opcode: OpCode) -> Self {
        match opcode {
            OpCode::STOP | OpCode::RETURN => 0,
            OpCode::JUMPDEST => 1,
            OpCode::ADDRESS
            | OpCode::ORIGIN
            | OpCode::CALLER
            | OpCode::CALLVALUE
            | OpCode::CODESIZE
            | OpCode::GASPRICE
            | OpCode::RETURNDATASIZE
            | OpCode::COINBASE
            | OpCode::TIMESTAMP
            | OpCode::NUMBER
            | OpCode::DIFFICULTY
            | OpCode::GASLIMIT
            | OpCode::CHAINID
            | OpCode::BASEFEE
            | OpCode::POP
            | OpCode::PC
            | OpCode::MSIZE
            | OpCode::GAS
            | OpCode::PUSH0 => 2,
            OpCode::MUL
            | OpCode::DIV
            | OpCode::SDIV
            | OpCode::MOD
            | OpCode::SMOD
            | OpCode::SIGNEXTEND
            | OpCode::SELFBALANCE => 5,
            OpCode::ADDMOD | OpCode::MULMOD | OpCode::JUMP => 8,
            OpCode::EXP | OpCode::JUMPI => 10,
            OpCode::BLOCKHASH => 20,
            OpCode::SHA3 => 30,
            OpCode::BALANCE
            | OpCode::EXTCODESIZE
            | OpCode::EXTCODECOPY
            | OpCode::EXTCODEHASH
            | OpCode::SLOAD
            | OpCode::SSTORE
            | OpCode::CALL
            | OpCode::CALLCODE
            | OpCode::DELEGATECALL
            | OpCode::STATICCALL => 100,
            OpCode::LOG0 => 375,
            OpCode::LOG1 => 750,
            OpCode::LOG2 => 1125,
            OpCode::LOG3 => 1500,
            OpCode::LOG4 => 1875,
            OpCode::SELFDESTRUCT => 5000,
            OpCode::CREATE | OpCode::CREATE2 => 32000,
            _ => 3,
        }
    }
}
